import {StyleSheet} from 'react-native'

import {useTheme} from '../../../hooks/themeProvider/themeProvider'

export const useStyles = ()=>{
    const theme = useTheme()

    return(
        StyleSheet.create({
            container:{
                flex:1,
                backgroundColor:theme.theme.backgroundColor,
                position:'relative'
            },
            header:{
                display:'flex',
                flexDirection:'row',
                justifyContent:'space-between',
                alignItems:'center',
                paddingHorizontal:5,
                paddingVertical:14,
                color:theme.theme.primaryTextColor,
            },
            leftContainer:{
                flexDirection:'row',
                alignItems:'center'
            },
            backButton:{
                color:theme.theme.primaryTextColor
            },
            pageNameContainer:{
                display:'flex',
                flexDirection:'row',
                alignItems:'center',
            },
            pageNameText:{
                fontSize:18,
                color:theme.theme.primaryTextColor,
                fontWeight:'bold'
            },
            themeButtonContainer:{
                flexDirection:'row',
                paddingHorizontal:15,
                paddingVertical:12,
                borderBottomColor:theme.theme.secondaryTextColor,
                borderBottomWidth:.5
            },
            themeButtonIconContainer:{
                justifyContent:'center',
                marginRight:35
            },
            themeButtonText:{
                color:theme.theme.primaryTextColor,
                fontSize:20,
            },
            themeModeText:{
                color:theme.theme.secondaryTextColor,
                marginTop:2
            },
            nameButtonContainer:{
                flexDirection:'row',
                paddingHorizontal:15,
                paddingVertical:12,
                borderBottomColor:theme.theme.secondaryTextColor,
                borderBottomWidth:.5
            },
            nameButtonIconContainer:{
                justifyContent:'center',
                marginRight:35
            },
            nameButtonText:{
                color:theme.theme.primaryTextColor,
                fontSize:20,   
            },
            nameText:{
                color:theme.theme.secondaryTextColor,
                marginTop:2
            },
            developerNameContainer:{
                flex:1,
                justifyContent:'flex-end',
                alignItems:'center',
                paddingBottom:5
            },
            fromText:{
                color:theme.theme.secondaryTextColor,
            },
            developerName:{
                color:theme.theme.primaryTextColor,
                fontWeight:'bold'
            }
        })
    )
}