import {StyleSheet} from 'react-native'

import {useTheme} from '../../hooks/themeProvider/themeProvider'

export const useStyles = ()=>{
    const theme = useTheme()

    return(
        StyleSheet.create({
            container:{
                flex:1,
                backgroundColor:theme.theme.backgroundColor,
                position:'relative'
            },
            myInfoContainer:{
                width:'100%',
                justifyContent:'center',
                alignItems:'center',
                paddingVertical:10,
                marginBottom:15,
            },
            myImageContainer:{
            },
            myImage:{
                width:150,
                height:150,
                borderRadius:75
            },
            cameraIconWrapper:{
                width:45,
                height:45,
                borderRadius:25,
                backgroundColor:theme.theme.activeColor,
                position:'absolute', 
                right:0,
                bottom:0
            },
            cameraIcon:{
                color:theme.theme.messageTextColor,
            },
            themeButtonContainer:{
                flexDirection:'row',
                paddingHorizontal:15,
                paddingVertical:12,
            },
            themeButtonIconContainer:{
                justifyContent:'center',
                marginRight:35
            },
            themeButtonText:{
                color:theme.theme.primaryTextColor,
                fontSize:18,
            },
            themeModeText:{
                color:theme.theme.secondaryTextColor,
                marginTop:2
            },
            nameButtonContainer:{
                flexDirection:'row',
                paddingHorizontal:15,
                paddingVertical:12,
            },
            nameButtonIconContainer:{
                justifyContent:'center',
                marginRight:35
            },
            nameButtonText:{
                color:theme.theme.primaryTextColor,
                fontSize:18,   
            },
            nameText:{
                color:theme.theme.secondaryTextColor,
                marginTop:2
            },
            developerNameContainer:{
                flex:1,
                justifyContent:'flex-end',
                alignItems:'center',
                paddingBottom:5
            },
            fromText:{
                color:theme.theme.secondaryTextColor,
            },
            developerName:{
                color:theme.theme.primaryTextColor,
                fontWeight:'bold'
            }
        })
    )
}